//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLabUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analyzis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analyzis()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Analyz { get; set; }
        public string NameAnalyz { get; set; }
        public int CostAnalyz { get; set; }
        public string Ogranizhenia { get; set; }
        public int TimeWork { get; set; }
        public int TypeAnalyz_ID { get; set; }
        public int Obrazech_ID { get; set; }
    
        public virtual Obrazchi Obrazchi { get; set; }
        public virtual TypeAnalyzies TypeAnalyzies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
