//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLabUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Client { get; set; }
        public string NameCompany { get; set; }
        public string EmailClient { get; set; }
        public Nullable<int> Dolznost_ID { get; set; }
        public string RekvisitOrganisation { get; set; }
        public string FirstNameC { get; set; }
        public string LastNameC { get; set; }
        public string PatronymicC { get; set; }
        public string Date_Born { get; set; }
        public string PolicyC { get; set; }
        public int TypeClient_ID { get; set; }
    
        public virtual Dolznosti Dolznosti { get; set; }
        public virtual TypeClient TypeClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
