//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLabUP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedLabEntities : DbContext
    {
        public MedLabEntities()
            : base("name=MedLabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Analyzis> Analyzis { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Dolznosti> Dolznosti { get; set; }
        public virtual DbSet<Obrazchi> Obrazchi { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payed> Payed { get; set; }
        public virtual DbSet<PayedType> PayedType { get; set; }
        public virtual DbSet<ResultAnalyzies> ResultAnalyzies { get; set; }
        public virtual DbSet<RoleWorker> RoleWorker { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<TypeAnalyzies> TypeAnalyzies { get; set; }
        public virtual DbSet<TypeClient> TypeClient { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
