//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLabUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ResultAnalyzies = new HashSet<ResultAnalyzies>();
        }
    
        public int ID_Order { get; set; }
        public int StatOrder_ID { get; set; }
        public int AddressoOrd_ID { get; set; }
        public string DateCreate { get; set; }
        public int Worker_ID { get; set; }
        public int Client_ID { get; set; }
        public int Analyz_ID { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Analyzis Analyzis { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultAnalyzies> ResultAnalyzies { get; set; }
    }
}
