//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLabUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payed
    {
        public int ID_Pay { get; set; }
        public string DatePay { get; set; }
        public int TypePay_ID { get; set; }
        public int Result_ID { get; set; }
    
        public virtual ResultAnalyzies ResultAnalyzies { get; set; }
        public virtual PayedType PayedType { get; set; }
    }
}
