//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLabUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Worker { get; set; }
        public int Role_ID { get; set; }
        public string Smeni { get; set; }
        public string LoginWorker { get; set; }
        public string PasswordWorker { get; set; }
        public string FirstNameW { get; set; }
        public string LastNameW { get; set; }
        public string PatronymicW { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual RoleWorker RoleWorker { get; set; }
    }
}
